apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: storage-topic
  labels:
    eventstreams.ibm.com/cluster: dev
spec:
  partitions: 1
  replicas: 3

---

apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: global-id-topic
  labels:
    eventstreams.ibm.com/cluster: dev
spec:
  partitions: 1
  replicas: 3

