apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: starter-app
  namespace: eventstreams-dev
  labels:
    eventstreams.ibm.com/cluster: dev
spec:
  partitions: 3 
  replicas: 3
  config:
    min.insync.replicas: 2
    cleanup.policy: delete
    retention.ms: 604800000
    segment.ms: 604800000
    delete.retention.ms: 86400000
    file.delete.delay.ms: 60000
    max.message.bytes: 1048588
    message.timestamp.type: LogAppendTime
