apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: dev
  namespace: eventstreams-dev
spec:
  version: 11.0.0
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  requestIbmServices:
    iam: true
    monitoring: true
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  security:
    internalTls: TLSv1.2
  strimziOverrides:
    entityOperator: 
      topicOperator:
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 90m
            memory: 2Gi
      userOperator:
        resources:
          limits:
            cpu: "1"
            memory: 1500Mi
          requests:
            cpu: 203m
            memory: 650Mi
    kafka:
      replicas: 3
      resources:
        requests:
          memory: 4Gi
          cpu: "1"
        limits:
          memory: 6Gi
          cpu: "2"
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: '3.0'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.cleaner.threads: 6
        log.message.format.version: '3.0'
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
      listeners:
        - name: plain
          type: internal
          port: 9092
          tls: false
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      storage:
        type: ephemeral
    zookeeper:
      replicas: 3
      storage:
        type: ephemeral
