# Important: The permission at the cluster resource must be All so that the Apicurio registry does not return {"message":"Cluster authorization failed.","error_code":500}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: tls-user
  labels:
    strimzi.io/cluster: my-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - host: '*'
        resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: cluster
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
--- 

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: scram-user
  labels:
    strimzi.io/cluster: my-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - host: '*'
        resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: cluster
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    