apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
- target:
    kind: Subscription
    name: elasticsearch-eck-operator-certified
  path: patch-channel.yaml
