apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: prod
  namespace: eventstreams-prod
spec:
  version: 10.4.0
  license:
    accept: true
    use: CloudPakForIntegrationProduction
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  cruiseControl: {}
  requestIbmServices:
    monitoring: true
    iam: true
  strimziOverrides:
    kafka:
      replicas: 3
      rack:
        topologyKey: topology.kubernetes.io/zone
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: '2.8'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.cleaner.threads: 6
        log.message.format.version: '2.8'
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        ssl.enabled.protocols: "TLSv1.2"
        ssl.protocol: "TLSv1.2"
      listeners:
        external:
          type: route
          authentication:
            type: scram-sha-512
        tls:
          authentication:
            type: tls
      metrics: {}
      resources:
        limits:
          cpu: 4000m
          memory: 8096Mi
        requests:
          cpu: 2000m
          memory: 4048Mi
      storage:
        type: persistent-claim
        size: 10Gi
        class: ibmc-block-gold
      entityOperator:
        topicOperator:
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: 90m
              memory: 2Gi
        userOperator:
          resources:
            limits:
              cpu: "1"
              memory: 1500Mi
            requests:
              cpu: 203m
              memory: 650Mi
    zookeeper:
      replicas: 3
      metrics: {}
      storage:
        type: persistent-claim
        size: 4Gi
        class: ibmc-block-gold
    cruiseControl: {}
