apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- github.com/redhat-cop/gitops-catalog//grafana-operator/base/operator?ref=main
- github.com/redhat-cop/gitops-catalog//grafana-operator/base/instance?ref=main

resources:
- grafana-ds.yaml
- patch-grafana-ds-sa.yaml
- patch-grafana-ds-job.yaml
- cluster-monitor-view-rb.yaml
