apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: openshift-operators
spec:
  channel: patch-me-see-overlays-dir
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace